
services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:16-alpine
    container_name: pos-postgres-dev
    restart: unless-stopped
    env_file: .env
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_DB: ${POSTGRES_DB:-pos_db}
      POSTGRES_USER: ${POSTGRES_USER:-pos_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pos_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5443:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - pos-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pos_user -d pos_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_dev_data:
    driver: local
  pgadmin_dev_data:
    driver: local

networks:
  pos-dev-network:
    driver: bridge
